import React, { useRef, useEffect } from 'react';
import PropTypes from 'prop-types';
import { View, StyleSheet, TouchableOpacity, Animated, Easing, ScrollView, ActivityIndicator, Linking, RefreshControl } from 'react-native';
import { Text, Divider, TouchableRipple } from 'react-native-paper';
import { Ionicons } from '@expo/vector-icons';
import { useThemeColors } from '../contexts/ThemeColorsContext';
import { useLocalization } from '../contexts/LocalizationContext';
import { HORIZONTAL_PADDING, SPACING, BORDER_RADIUS } from '../styles/layout';

const DATE_RE = /(\d{4}-\d{2}-\d{2})/;
const PR_RE = /#(\d+)/g;

const stripMarkdown = (md) => md
  .replace(/\r\n/g, '\n')
  .replace(/#{1,6}\s+/g, '')
  .replace(/\*\*(.+?)\*\*/g, '$1')
  .replace(/\*(.+?)\*/g, '$1')
  .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
  .replace(/`([^`]+)`/g, '$1')
  .replace(/^\s*[-*+]\s+/gm, '• ')
  .replace(/\n{3,}/g, '\n\n')
  .trim();

// Splits the release body off from its leading "version (date)" heading.
// Release notes generated by semantic-release start with a markdown heading such as
// "## 0.134.15 (2026-06-17)" which duplicates the version we already show. We lift the
// date out of that heading (to render it inline beside the version) and drop the line
// from the body so it isn't shown twice.
export const parseReleaseNotes = (notes, version) => {
  const cleaned = (notes || '').replace(/\r\n/g, '\n');
  const lines = cleaned.split('\n');

  let date = null;
  let firstContentIdx = -1;
  for (let i = 0; i < lines.length; i += 1) {
    if (lines[i].trim()) {
      firstContentIdx = i;
      break;
    }
  }

  let bodyLines = lines;
  if (firstContentIdx >= 0) {
    const firstLine = lines[firstContentIdx];
    const trimmed = firstLine.trim();
    const isHeading = /^#{1,6}\s/.test(firstLine);
    const hasDate = DATE_RE.test(trimmed);
    const hasVersion = version && trimmed.includes(version);
    if (isHeading && (hasDate || hasVersion)) {
      const match = trimmed.match(DATE_RE);
      if (match) {
        [, date] = match;
      }
      bodyLines = lines.slice(firstContentIdx + 1);
    }
  }

  return { date, body: stripMarkdown(bodyLines.join('\n')) };
};

// Derives the repository base URL (e.g. https://github.com/owner/repo) from the
// releases URL so we can build links to individual pull requests.
const repoBaseFromReleasesUrl = (releasesUrl) => {
  if (!releasesUrl || typeof releasesUrl !== 'string') return null;
  return releasesUrl.replace(/\/releases\/?$/, '');
};

// Renders release-note text, turning "#123" pull-request references into tappable links.
const renderNotesWithLinks = (text, repoBase, linkColor) => {
  if (!text) return null;
  if (!repoBase) return text;

  const segments = [];
  let lastIndex = 0;
  let match;
  PR_RE.lastIndex = 0;
  while ((match = PR_RE.exec(text)) !== null) {
    if (match.index > lastIndex) {
      segments.push(text.slice(lastIndex, match.index));
    }
    const prNumber = match[1];
    segments.push(
      <Text
        key={`pr-${match.index}`}
        style={[styles.prLink, { color: linkColor }]}
        onPress={() => Linking.openURL(`${repoBase}/pull/${prNumber}`)}
        accessibilityRole="link"
        accessibilityLabel={`Pull request ${prNumber}`}
      >
        #{prNumber}
      </Text>,
    );
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < text.length) {
    segments.push(text.slice(lastIndex));
  }
  return segments;
};

const formatApkDate = (modificationTime) => {
  if (!modificationTime) return '';
  return new Date(modificationTime * 1000).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
};

// Green used for the "installed / up to date" status, matching the checkmark elsewhere in this panel.
const INSTALLED_GREEN = '#4caf50';
// Amber used to warn that a corrupt cached download was discarded and is being re-downloaded.
const WARNING_AMBER = '#f0a500';

function ReleaseCard({ version, notes, badge, buildProgress, matchedApk, repoBase, onInstallApk, colors, t, isInstalled, isLatestInstalled, isUpdateCandidate }) {
  const { date, body } = parseReleaseNotes(notes, version);
  const spinAnim = useRef(new Animated.Value(0)).current;
  useEffect(() => {
    if (!buildProgress) return undefined;
    const loop = Animated.loop(
      Animated.timing(spinAnim, { toValue: 1, duration: 1500, easing: Easing.linear, useNativeDriver: true }),
    );
    loop.start();
    return () => { loop.stop(); spinAnim.setValue(0); };
  }, [buildProgress, spinAnim]);
  // We highlight a single card: the candidate for installation when an update is available,
  // otherwise the installed-and-latest card when we are already up to date. The candidate
  // takes the primary accent; the up-to-date installed card keeps the green "latest" accent.
  const highlighted = isUpdateCandidate || isLatestInstalled;
  const accent = isLatestInstalled ? INSTALLED_GREEN : colors.primary;
  // Once an update is available the installed card is no longer the highlighted one, so its
  // "Installed" chip recedes to a muted, purely informational treatment.
  const installedChipColor = isLatestInstalled ? accent : colors.mutedText;
  return (
    <View
      style={[
        styles.releaseCard,
        { backgroundColor: colors.surface, borderColor: highlighted ? accent : colors.border },
        highlighted && styles.releaseCardHighlighted,
      ]}
    >
      <View style={styles.releaseHeader}>
        <View style={styles.releaseHeaderLeft}>
          <Text style={[styles.releaseVersion, { color: colors.text }]}>v{version}</Text>
          {date ? (
            <Text style={[styles.releaseDate, { color: colors.mutedText }]}>{date}</Text>
          ) : null}
          {badge ? (
            <Text style={[styles.releaseBadge, { color: colors.mutedText, borderColor: colors.border }]}>
              {badge}
            </Text>
          ) : null}
          {buildProgress && typeof buildProgress.percent === 'number' ? (
            <View
              style={[styles.buildProgressChip, { borderColor: colors.primary }]}
              accessibilityRole="text"
              accessibilityLabel={(t('build_in_progress') || 'Building {percent}%').replace('{percent}', String(buildProgress.percent))}
            >
              <Animated.View style={{ transform: [{ rotate: spinAnim.interpolate({ inputRange: [0, 1], outputRange: ['0deg', '360deg'] }) }] }}>
                <Ionicons name="sync-outline" size={13} color={colors.primary} />
              </Animated.View>
              <Text style={[styles.buildProgressText, { color: colors.primary }]}>
                {(t('build_in_progress') || 'Building {percent}%').replace('{percent}', String(buildProgress.percent))}
              </Text>
            </View>
          ) : null}
          {isUpdateCandidate ? (
            <View
              style={[styles.installedChip, { borderColor: colors.primary }]}
              accessibilityRole="text"
              accessibilityLabel={t('update_candidate') || 'Available to install'}
            >
              <Ionicons name="arrow-up-circle" size={13} color={colors.primary} />
              <Text style={[styles.installedChipText, { color: colors.primary }]}>
                {t('update_candidate') || 'Available'}
              </Text>
            </View>
          ) : null}
          {isInstalled ? (
            <View
              style={[styles.installedChip, { borderColor: installedChipColor }]}
              accessibilityRole="text"
              accessibilityLabel={isLatestInstalled
                ? (t('installed_latest_hint') || 'Installed — you are on the latest version')
                : (t('installed') || 'Installed')}
            >
              {isLatestInstalled ? (
                <Ionicons name="checkmark-circle" size={13} color={accent} />
              ) : null}
              <Text style={[styles.installedChipText, { color: installedChipColor }]}>
                {t('installed') || 'Installed'}
              </Text>
            </View>
          ) : null}
        </View>
        {matchedApk ? (
          <TouchableOpacity
            onPress={() => onInstallApk(matchedApk.uri)}
            style={styles.releaseApkButton}
            accessibilityRole="button"
            accessibilityLabel={`Install version ${version}`}
          >
            <Ionicons name="archive-outline" size={18} color={colors.primary} />
            <Ionicons name="download-outline" size={14} color={colors.primary} />
          </TouchableOpacity>
        ) : null}
      </View>
      {isLatestInstalled ? (
        <View style={styles.installedHintRow}>
          <Ionicons name="information-circle-outline" size={13} color={INSTALLED_GREEN} />
          <Text style={[styles.installedHintText, { color: INSTALLED_GREEN }]}>
            {t('installed_latest_hint') || "You're on the latest version."}
          </Text>
        </View>
      ) : null}
      {body ? (
        <Text style={[styles.releaseBody, { color: colors.text }]}>
          {renderNotesWithLinks(body, repoBase, colors.primary)}
        </Text>
      ) : null}
    </View>
  );
}

ReleaseCard.propTypes = {
  version: PropTypes.string,
  notes: PropTypes.string,
  badge: PropTypes.string,
  buildProgress: PropTypes.shape({
    percent: PropTypes.number,
  }),
  matchedApk: PropTypes.object,
  repoBase: PropTypes.string,
  onInstallApk: PropTypes.func,
  colors: PropTypes.object,
  t: PropTypes.func,
  isInstalled: PropTypes.bool,
  isLatestInstalled: PropTypes.bool,
  isUpdateCandidate: PropTypes.bool,
};

function MoreReleasesLink({ url, colors, t }) {
  return (
    <TouchableOpacity onPress={() => Linking.openURL(url)} style={styles.moreReleasesLink}>
      <Text style={[styles.moreReleasesLinkText, { color: colors.primary }]}>
        {t('more_releases') || 'More on GitHub'}
      </Text>
      <Ionicons name="open-outline" size={14} color={colors.primary} />
    </TouchableOpacity>
  );
}

MoreReleasesLink.propTypes = {
  url: PropTypes.string,
  colors: PropTypes.object,
  t: PropTypes.func,
};

// Compact list of downloaded APKs that did not line up with a release shown above.
function UnmatchedApks({ apks, onInstallApk, colors, t, compact }) {
  if (!apks.length) return null;
  return (
    <View style={compact ? styles.downloadedApksCompact : styles.downloadedApksSection}>
      <Text style={[compact ? styles.downloadedApksTitleCompact : styles.downloadedApksTitle, { color: colors.mutedText }]}>
        {t('downloaded_apks') || 'Downloaded APKs'}
      </Text>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.apkListContent}>
        {apks.map((item) => (
          <TouchableOpacity
            key={item.uri}
            onPress={() => onInstallApk(item.uri)}
            style={styles.apkChipCompact}
            accessibilityRole="button"
            accessibilityLabel={`Install version ${item.version || item.filename}`}
          >
            <Ionicons name="archive-outline" size={22} color={colors.primary} />
            <Text style={[styles.apkChipVersion, { color: colors.text }]}>
              {item.version ? `v${item.version}` : item.filename.replace(/\.apk$/i, '')}
            </Text>
            <Text style={[styles.apkChipDate, { color: colors.mutedText }]}>
              {formatApkDate(item.modificationTime)}
            </Text>
          </TouchableOpacity>
        ))}
      </ScrollView>
    </View>
  );
}

UnmatchedApks.propTypes = {
  apks: PropTypes.array,
  onInstallApk: PropTypes.func,
  colors: PropTypes.object,
  t: PropTypes.func,
  compact: PropTypes.bool,
};

const buildApkLookup = (downloadedApks) => {
  const map = new Map();
  downloadedApks.forEach((apk) => {
    if (apk.version && !map.has(apk.version)) {
      map.set(apk.version, apk);
    }
  });
  return map;
};

const unmatchedApksFor = (downloadedApks, releases) => {
  const shown = new Set(releases.map((r) => r.version));
  return downloadedApks.filter((apk) => !apk.version || !shown.has(apk.version));
};

export default function UpdateContentPanel({ isChecking, updateResult, downloadedApks, onUpdate, onInstallApk, onRefresh }) {
  const { colors } = useThemeColors();
  const { t } = useLocalization();
  const contentAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    if (isChecking) {
      contentAnim.setValue(0);
    }
  }, [isChecking, contentAnim]);

  useEffect(() => {
    if (!isChecking && updateResult) {
      Animated.timing(contentAnim, {
        toValue: 1,
        duration: 280,
        easing: Easing.out(Easing.quad),
        useNativeDriver: true,
      }).start();
    }
  }, [isChecking, updateResult, contentAnim]);

  if (isChecking) {
    return (
      <View style={styles.checkingContainer}>
        <ActivityIndicator size="large" color={colors.primary} />
        <Text style={[styles.checkingText, { color: colors.text }]}>
          {t('checking_for_updates') || 'Checking for available updates…'}
        </Text>
      </View>
    );
  }

  if (!updateResult) return null;

  const repoBase = repoBaseFromReleasesUrl(updateResult.releasesUrl);
  const apkLookup = buildApkLookup(downloadedApks);

  // The currently installed app version. We treat it as the latest — green checkmark + hint —
  // whenever there is no newer *installable* release. That covers two cases: being fully up to
  // date, and a newer release existing but having no APK attached yet (CI build still running).
  // In the latter case the user still holds the newest installable APK, so the installed version
  // is the latest one they can actually run.
  const installedVersion = updateResult.currentVersion;
  const installedIsLatest = updateResult.type === 'up_to_date'
    || (updateResult.type === 'error' && updateResult.errorCode === 'releases_without_apks');
  // When an update is available, the release we want the user to install is the highlighted
  // one — not the version they already have.
  const candidateVersion = updateResult.type === 'available' ? updateResult.latestVersion : null;

  const renderReleaseCards = (releases) => releases.map((release) => {
    const isInstalled = !!installedVersion && release.version === installedVersion;
    const isUpdateCandidate = !!candidateVersion && release.version === candidateVersion;
    return (
      <ReleaseCard
        key={release.version}
        version={release.version}
        notes={release.notes}
        badge={release.badge}
        buildProgress={release.buildProgress}
        matchedApk={apkLookup.get(release.version)}
        repoBase={repoBase}
        onInstallApk={onInstallApk}
        colors={colors}
        t={t}
        isInstalled={isInstalled}
        isLatestInstalled={isInstalled && installedIsLatest}
        isUpdateCandidate={isUpdateCandidate}
      />
    );
  });

  return (
    <Animated.View style={[styles.resultContainer, { opacity: contentAnim }]}>
      {updateResult.type === 'available' && (() => {
        const releaseNotes = updateResult.recentReleaseNotes || updateResult.releaseNotes;
        const releases = releaseNotes || [];
        const unmatched = unmatchedApksFor(downloadedApks, releases);
        return (
          <>
            {releaseNotes ? (
              <>
                <Text style={[styles.changelogTitle, { color: colors.mutedText }]}>
                  {t('whats_new') || "What's new"}
                </Text>
                <ScrollView
                  style={styles.changelogScroll}
                  showsVerticalScrollIndicator={false}
                  refreshControl={onRefresh ? <RefreshControl refreshing={false} onRefresh={onRefresh} /> : undefined}
                >
                  {renderReleaseCards(releases)}
                  {updateResult.releasesUrl && (
                    <MoreReleasesLink url={updateResult.releasesUrl} colors={colors} t={t} />
                  )}
                </ScrollView>
              </>
            ) : (
              <Text style={[styles.updateVersionText, { color: colors.mutedText }]}>
                {t('update_install_hint') || 'If installation is blocked, allow "Install unknown apps" for your browser or file manager in Android settings.'}
              </Text>
            )}
            <Divider style={styles.updateDivider} />
            {updateResult.previousDownloadCorrupted ? (
              <View style={styles.corruptNoteRow} accessibilityRole="text">
                <Ionicons name="alert-circle-outline" size={14} color={WARNING_AMBER} />
                <Text style={[styles.corruptNoteText, { color: WARNING_AMBER }]}>
                  {t('apk_corrupt_redownload') || 'The previous download was damaged and was removed. Tap Update now to download it again.'}
                </Text>
              </View>
            ) : null}
            <View style={styles.updateBottomRow}>
              {releaseNotes ? (
                <UnmatchedApks apks={unmatched} onInstallApk={onInstallApk} colors={colors} t={t} compact />
              ) : (
                <UnmatchedApks apks={downloadedApks} onInstallApk={onInstallApk} colors={colors} t={t} compact />
              )}
              <View style={styles.updateActionColumn}>
                <Text style={[styles.updateButtonVersion, { color: colors.text }]}>
                  v{updateResult.latestVersion}
                </Text>
                <Text style={[styles.updateButtonCurrentVersion, { color: colors.mutedText }]}>
                  {(t('update_from_version') || 'installed: v{currentVersion}')
                    .replace('{currentVersion}', updateResult.currentVersion)}
                </Text>
                <TouchableRipple
                  onPress={() => {
                    if (updateResult.alreadyDownloaded) {
                      onInstallApk(updateResult.localUri);
                    } else {
                      onUpdate(updateResult.downloadUrl, updateResult.checksumUrl);
                    }
                  }}
                  style={[styles.updateButtonCompact, { backgroundColor: colors.primary }]}
                >
                  <Text style={styles.updateButtonText}>
                    {updateResult.alreadyDownloaded
                      ? (t('update_install_now') || 'Install now')
                      : (t('update_now') || 'Update now')}
                  </Text>
                </TouchableRipple>
              </View>
            </View>
          </>
        );
      })()}

      {updateResult.type === 'up_to_date' && (
        <View style={styles.upToDateContent}>
          {updateResult.recentReleaseNotes ? (() => {
            const releases = updateResult.recentReleaseNotes;
            const unmatched = unmatchedApksFor(downloadedApks, releases);
            // The installed version is also the latest one here, so it is rendered as a
            // green-highlighted card carrying the "you're on the latest version" hint inline.
            // Only fall back to a standalone bottom status when that card is absent (the
            // installed version isn't among the listed releases).
            const latestShownOnCard = !!installedVersion && releases.some((r) => r.version === installedVersion);
            return (
              <>
                <Text style={[styles.changelogTitle, { color: colors.mutedText }]}>
                  {t('release_history') || 'Release history'}
                </Text>
                <ScrollView
                  style={styles.changelogScroll}
                  showsVerticalScrollIndicator={false}
                  refreshControl={onRefresh ? <RefreshControl refreshing={false} onRefresh={onRefresh} /> : undefined}
                >
                  {renderReleaseCards(releases)}
                  {updateResult.releasesUrl && (
                    <MoreReleasesLink url={updateResult.releasesUrl} colors={colors} t={t} />
                  )}
                </ScrollView>
                {(unmatched.length > 0 || !latestShownOnCard) && (
                  <>
                    <Divider style={styles.updateDivider} />
                    <View style={styles.updateBottomRow}>
                      <UnmatchedApks apks={unmatched} onInstallApk={onInstallApk} colors={colors} t={t} compact />
                      {!latestShownOnCard ? (
                        <View style={styles.upToDateBottomRight}>
                          <Ionicons name="checkmark-circle-outline" size={24} color="#4caf50" />
                          <Text style={[styles.upToDateHeaderText, { color: colors.text }]}>
                            {t('up_to_date') || 'You already have the latest version installed.'}
                          </Text>
                        </View>
                      ) : null}
                    </View>
                  </>
                )}
              </>
            );
          })() : (
            <>
              <View style={styles.upToDateHeaderSpacer}>
                <View style={styles.upToDateHeader}>
                  <Ionicons name="checkmark-circle-outline" size={48} color="#4caf50" style={styles.centeredIcon} />
                  <Text style={[styles.updateVersionText, { color: colors.text }]}>
                    {t('up_to_date') || 'You already have the latest version installed.'}
                  </Text>
                </View>
              </View>
              {downloadedApks.length > 0 && (
                <View style={styles.downloadedApksSection}>
                  <Divider />
                  <UnmatchedApks apks={downloadedApks} onInstallApk={onInstallApk} colors={colors} t={t} />
                </View>
              )}
            </>
          )}
        </View>
      )}

      {updateResult.type === 'error' && updateResult.errorCode === 'releases_without_apks' && (updateResult.releaseNotes || updateResult.recentReleaseNotes) ? (() => {
        // Surface CI build progress on the newest release awaiting its APK — that is the build
        // currently running. Older no-APK releases (if any) get no progress chip.
        let buildProgressShown = false;
        const noApkReleases = (updateResult.releaseNotes || []).map((r) => {
          const showProgress = !r.hasApk && !buildProgressShown && !!updateResult.buildProgress;
          if (showProgress) buildProgressShown = true;
          return {
            version: r.version,
            notes: r.notes,
            badge: !r.hasApk ? (t('no_apk_attached') || 'NO_APK_ATTACHED') : undefined,
            buildProgress: showProgress ? updateResult.buildProgress : null,
          };
        });
        const recentReleases = updateResult.recentReleaseNotes || [];
        return (
          <View style={styles.upToDateContent}>
            <Text style={[styles.changelogTitle, { color: colors.mutedText }]}>
              {t('release_history') || 'Release history'}
            </Text>
            <ScrollView
              style={styles.changelogScroll}
              showsVerticalScrollIndicator={false}
              refreshControl={onRefresh ? <RefreshControl refreshing={false} onRefresh={onRefresh} /> : undefined}
            >
              {renderReleaseCards(noApkReleases)}
              {renderReleaseCards(recentReleases)}
              {updateResult.releasesUrl && (
                <MoreReleasesLink url={updateResult.releasesUrl} colors={colors} t={t} />
              )}
            </ScrollView>
          </View>
        );
      })() : updateResult.type === 'error' && (
        <View style={styles.errorContent}>
          <Ionicons name="cloud-offline-outline" size={48} color={colors.mutedText} style={styles.centeredIcon} />
          <Text style={[styles.updateVersionText, { color: colors.text }]}>
            {updateResult.errorCode === 'releases_without_apks'
              ? (t('update_releases_without_apks') || 'Found releases but no APKs attached. Check GitHub for the latest release.')
              : (t('update_check_failed') || 'Could not check updates right now. Please try again later.')}
          </Text>
        </View>
      )}
    </Animated.View>
  );
}

UpdateContentPanel.propTypes = {
  isChecking: PropTypes.bool,
  updateResult: PropTypes.shape({
    type: PropTypes.oneOf(['available', 'up_to_date', 'error']).isRequired,
    latestVersion: PropTypes.string,
    currentVersion: PropTypes.string,
    downloadUrl: PropTypes.string,
    checksumUrl: PropTypes.string,
    releaseNotes: PropTypes.arrayOf(PropTypes.shape({
      version: PropTypes.string,
      notes: PropTypes.string,
      hasApk: PropTypes.bool,
    })),
    recentReleaseNotes: PropTypes.arrayOf(PropTypes.shape({
      version: PropTypes.string,
      notes: PropTypes.string,
    })),
    releasesUrl: PropTypes.string,
    alreadyDownloaded: PropTypes.bool,
    localUri: PropTypes.string,
    previousDownloadCorrupted: PropTypes.bool,
    errorCode: PropTypes.string,
    buildProgress: PropTypes.shape({
      percent: PropTypes.number,
    }),
  }),
  downloadedApks: PropTypes.array,
  onUpdate: PropTypes.func,
  onInstallApk: PropTypes.func,
  onRefresh: PropTypes.func,
};

UpdateContentPanel.defaultProps = {
  isChecking: false,
  updateResult: null,
  downloadedApks: [],
  onUpdate: () => {},
  onInstallApk: () => {},
  onRefresh: null,
};

const styles = StyleSheet.create({
  apkChipCompact: {
    alignItems: 'center',
    gap: SPACING.xs,
    minWidth: 44,
    paddingHorizontal: SPACING.xs,
    paddingVertical: SPACING.sm,
  },
  apkChipDate: {
    fontSize: 11,
    textAlign: 'center',
  },
  apkChipVersion: {
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  apkListContent: {
    paddingHorizontal: SPACING.sm,
  },
  buildProgressChip: {
    alignItems: 'center',
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 2,
    paddingHorizontal: SPACING.xs,
    paddingVertical: 1,
  },
  buildProgressText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  centeredIcon: {
    marginBottom: SPACING.lg,
  },
  changelogScroll: {
    flex: 1,
    marginTop: SPACING.sm,
  },
  changelogTitle: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.8,
    marginTop: SPACING.md,
    textTransform: 'uppercase',
  },
  checkingContainer: {
    alignItems: 'center',
    flex: 1,
    gap: SPACING.lg,
    justifyContent: 'center',
    paddingHorizontal: HORIZONTAL_PADDING * 2,
  },
  checkingText: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  corruptNoteRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: SPACING.xs,
    paddingTop: SPACING.sm,
  },
  corruptNoteText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 17,
  },
  downloadedApksCompact: {
    flex: 1,
    overflow: 'hidden',
  },
  downloadedApksSection: {
    paddingBottom: SPACING.md,
  },
  downloadedApksTitle: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    paddingBottom: SPACING.sm,
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingTop: SPACING.md,
    textTransform: 'uppercase',
  },
  downloadedApksTitleCompact: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    paddingBottom: SPACING.sm,
    textTransform: 'uppercase',
  },
  errorContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: HORIZONTAL_PADDING * 2,
    paddingVertical: SPACING.xl,
  },
  installedChip: {
    alignItems: 'center',
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 2,
    paddingHorizontal: SPACING.xs,
    paddingVertical: 1,
  },
  installedChipText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  installedHintRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: SPACING.xs,
    marginBottom: SPACING.sm,
    paddingLeft: SPACING.sm,
  },
  installedHintText: {
    fontSize: 12,
    fontWeight: '500',
  },
  moreReleasesLink: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: SPACING.xs,
    paddingBottom: SPACING.md,
    paddingTop: SPACING.xs,
  },
  moreReleasesLinkText: {
    fontSize: 13,
    fontWeight: '600',
  },
  prLink: {
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  releaseApkButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 1,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
  },
  releaseBadge: {
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: StyleSheet.hairlineWidth,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.5,
    overflow: 'hidden',
    paddingHorizontal: SPACING.xs,
    paddingVertical: 1,
    textTransform: 'uppercase',
  },
  releaseBody: {
    fontSize: 13,
    lineHeight: 20,
    paddingLeft: SPACING.sm,
  },
  releaseCard: {
    borderRadius: BORDER_RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    marginBottom: SPACING.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
  },
  releaseCardHighlighted: {
    borderWidth: 1.5,
  },
  releaseDate: {
    fontSize: 12,
    fontWeight: '500',
  },
  releaseHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: SPACING.sm,
  },
  releaseHeaderLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  releaseVersion: {
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  resultContainer: {
    flex: 1,
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingVertical: SPACING.lg,
  },
  upToDateBottomRight: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    gap: SPACING.sm,
    justifyContent: 'flex-end',
    paddingVertical: SPACING.sm,
  },
  upToDateContent: {
    flex: 1,
  },
  upToDateHeader: {
    alignItems: 'center',
    paddingHorizontal: HORIZONTAL_PADDING * 2,
  },
  upToDateHeaderSpacer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  upToDateHeaderText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  updateActionColumn: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-end',
  },
  updateBottomRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
    paddingTop: SPACING.sm,
  },
  updateButtonCompact: {
    alignSelf: 'stretch',
    borderRadius: BORDER_RADIUS.md,
    marginTop: SPACING.xs,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
  },
  updateButtonCurrentVersion: {
    fontSize: 11,
    marginTop: 2,
    textAlign: 'center',
  },
  updateButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  updateButtonVersion: {
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  updateDivider: {
    marginTop: SPACING.sm,
  },
  updateVersionText: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
});
