const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Expo Config Plugin: give Penny's two bank alerts *different* status-bar icons.
 *
 * Android picks a notification's small icon per notification, but
 * expo-notifications only exposes one app-wide icon (its config plugin writes the
 * `expo.modules.notifications.default_notification_icon` manifest meta-data, and
 * `ExpoNotificationBuilder` reads it for every notification it builds). There is
 * no JS-side field for the small icon, so the per-notification choice has to be
 * made natively.
 *
 * expo-notifications is built for exactly this: its receiver is declared at
 * intent-filter priority -1, every delegate getter is `open`, and dispatch goes
 * through `queryBroadcastReceivers(...).firstOrNull()` — so an app-level receiver
 * at the default priority 0 takes over notification work simply by existing. This
 * plugin declares that receiver and generates the three small classes behind it:
 *
 *   PennyNotificationsService   -> hands presentation to our delegate
 *   PennyPresentationDelegate   -> builds notifications with our builder
 *   PennyNotificationBuilder    -> overrides `icon` based on the alert's route
 *
 * Everything else — routing taps, action buttons, dismissal, scheduling — stays
 * with expo-notifications' own delegates, inherited untouched.
 *
 * The icon is chosen from the `route` value already carried in each alert's data
 * payload (see app/services/notifications/localNotifications.js), so no JS change
 * is needed to pick it, and an unrecognised route falls back to the app-wide icon
 * rather than to nothing.
 *
 * The two drawables are checked-in vector XML (assets/android-drawables/),
 * generated by scripts/generate-notification-icon.js; the android/ folder is
 * gitignored (managed workflow), so they are copied in at prebuild time.
 */

const ANDROID_PACKAGE = 'com.heywood8.monkeep';
const SERVICE_CLASS = 'PennyNotificationsService';
const DELEGATE_CLASS = 'PennyPresentationDelegate';
const BUILDER_CLASS = 'PennyNotificationBuilder';

/** The action expo-notifications dispatches all notification work on. */
const NOTIFICATION_EVENT_ACTION = 'expo.modules.notifications.NOTIFICATION_EVENT';

/**
 * Drawables copied into res/drawable, and the payload routes they belong to.
 * The route strings must stay in step with ROUTE_PENDING_OPERATIONS and
 * ROUTE_ADDED_OPERATIONS in app/services/notifications/localNotifications.js —
 * a mismatch silently falls back to the default icon, so a test asserts they
 * match (__tests__/plugins/withNotificationIcons.test.js).
 */
const ICONS = [
  { drawable: 'notification_icon_pending', route: 'notificationProcessing' },
  { drawable: 'notification_icon_added', route: 'addedOperations' },
];

/** Key under which the route travels in the notification's data payload. */
const ROUTE_KEY = 'route';

const DRAWABLES_SOURCE_DIR = path.join('assets', 'android-drawables');

const BUILDER_SOURCE = `package ${ANDROID_PACKAGE}

import android.content.Context
import expo.modules.notifications.notifications.model.Notification
import expo.modules.notifications.notifications.presentation.builders.ExpoNotificationBuilder
import expo.modules.notifications.service.delegates.SharedPreferencesNotificationCategoriesStore

/**
 * Notification builder that picks the status-bar icon per alert.
 *
 * The two bank alerts ask for different things — one is a task ("transactions to
 * review"), the other a receipt ("operations added") — and telling them apart
 * should not require pulling the shade down. Everything except the icon is
 * [ExpoNotificationBuilder]'s.
 */
class ${BUILDER_CLASS}(
    context: Context,
    notification: Notification,
    store: SharedPreferencesNotificationCategoriesStore,
) : ExpoNotificationBuilder(context, notification, store) {
    override val icon: Int
        get() = when (notificationContent.body?.optString(ROUTE_KEY)) {
${ICONS.map((icon) => `            ${constantName(icon.route)} -> R.drawable.${icon.drawable}`).join('\n')}
            // Not one of ours (or no payload): keep the app-wide default icon.
            else -> super.icon
        }

    companion object {
        private const val ROUTE_KEY = "${ROUTE_KEY}"
${ICONS.map((icon) => `        private const val ${constantName(icon.route)} = "${icon.route}"`).join('\n')}
    }
}
`;

const DELEGATE_SOURCE = `package ${ANDROID_PACKAGE}

import android.content.Context
import expo.modules.notifications.notifications.model.Notification
import expo.modules.notifications.notifications.model.NotificationBehaviorRecord
import expo.modules.notifications.service.delegates.ExpoPresentationDelegate
import expo.modules.notifications.service.delegates.SharedPreferencesNotificationCategoriesStore

/**
 * Presentation delegate that swaps in [${BUILDER_CLASS}]. Presenting,
 * dismissing and reading back notifications stay as expo-notifications does them.
 */
class ${DELEGATE_CLASS}(context: Context) : ExpoPresentationDelegate(context) {
    override suspend fun createNotification(
        notification: Notification,
        notificationBehavior: NotificationBehaviorRecord?,
    ): android.app.Notification =
        ${BUILDER_CLASS}(
            context,
            notification,
            SharedPreferencesNotificationCategoriesStore(context),
        ).apply { setAllowedBehavior(notificationBehavior) }.build()
}
`;

const SERVICE_SOURCE = `package ${ANDROID_PACKAGE}

import android.content.Context
import expo.modules.notifications.service.NotificationsService
import expo.modules.notifications.service.interfaces.PresentationDelegate

/**
 * Takes over notification work from expo-notifications' own receiver.
 *
 * expo-notifications resolves the receiver to dispatch to with
 * queryBroadcastReceivers().firstOrNull(), which returns the highest-priority
 * match; its own receiver sits at priority -1, so this one (declared at the
 * default 0) wins. Only the presentation delegate is replaced — handling,
 * categories and scheduling are inherited.
 */
class ${SERVICE_CLASS} : NotificationsService() {
    override fun getPresentationDelegate(context: Context): PresentationDelegate =
        ${DELEGATE_CLASS}(context)
}
`;

/** Kotlin constant name for a route, e.g. addedOperations -> ROUTE_ADDED_OPERATIONS. */
function constantName(route) {
  return `ROUTE_${route.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()}`;
}

/**
 * Declares the receiver that takes over notification dispatch.
 *
 * Only the notification-event action is claimed: BOOT_COMPLETED and friends are
 * system broadcasts delivered to *every* matching receiver rather than to the
 * highest-priority one, so re-declaring them here would run expo's boot work
 * twice instead of once.
 */
const addReceiverToManifest = (config) =>
  withAndroidManifest(config, (config) => {
    const application = config.modResults.manifest.application?.[0];
    if (!application) {
      throw new Error(
        'withNotificationIcons: <application> not found in AndroidManifest.xml',
      );
    }

    application.receiver = application.receiver || [];

    const receiverName = `.${SERVICE_CLASS}`;
    const alreadyDeclared = application.receiver.some(
      (receiver) => receiver?.$?.['android:name'] === receiverName,
    );

    if (!alreadyDeclared) {
      application.receiver.push({
        $: {
          'android:name': receiverName,
          'android:enabled': 'true',
          // Only expo-notifications' own code broadcasts to it, from inside the
          // app; nothing external needs to reach it.
          'android:exported': 'false',
        },
        'intent-filter': [
          {
            $: { 'android:priority': '0' },
            action: [{ $: { 'android:name': NOTIFICATION_EVENT_ACTION } }],
          },
        ],
      });
    }

    return config;
  });

/**
 * Copies the per-alert vector drawables into res/drawable and writes the native
 * Kotlin sources. The android/ folder is managed by Expo (gitignored), so both
 * have to be (re)generated at prebuild time.
 */
const addNativeSources = (config) =>
  withDangerousMod(config, [
    'android',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;

      const drawableDir = path.join(
        projectRoot,
        'android',
        'app',
        'src',
        'main',
        'res',
        'drawable',
      );
      fs.mkdirSync(drawableDir, { recursive: true });
      ICONS.forEach(({ drawable }) => {
        const filename = `${drawable}.xml`;
        fs.copyFileSync(
          path.join(projectRoot, DRAWABLES_SOURCE_DIR, filename),
          path.join(drawableDir, filename),
        );
      });

      const targetDir = path.join(
        projectRoot,
        'android',
        'app',
        'src',
        'main',
        'java',
        ...ANDROID_PACKAGE.split('.'),
      );
      fs.mkdirSync(targetDir, { recursive: true });
      [
        [`${BUILDER_CLASS}.kt`, BUILDER_SOURCE],
        [`${DELEGATE_CLASS}.kt`, DELEGATE_SOURCE],
        [`${SERVICE_CLASS}.kt`, SERVICE_SOURCE],
      ].forEach(([filename, source]) => {
        fs.writeFileSync(path.join(targetDir, filename), source);
      });

      console.log(
        '✅ Wrote per-alert notification icons (2 drawables, 3 native sources)',
      );

      return config;
    },
  ]);

const withNotificationIcons = (config) => {
  config = addReceiverToManifest(config);
  config = addNativeSources(config);
  return config;
};

module.exports = withNotificationIcons;
module.exports.ICONS = ICONS;
module.exports.ROUTE_KEY = ROUTE_KEY;
